// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA15thrGsTgKOdtMqFsUeJEuRE9Z3b6gMY',
    appId: '1:549553278454:web:585c46381a5f418134cbd7',
    messagingSenderId: '549553278454',
    projectId: 'no-doubt-f8f3e',
    authDomain: 'no-doubt-f8f3e.firebaseapp.com',
    storageBucket: 'no-doubt-f8f3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5OHrVnR1UmX6E5aWo0MOsh7zE3XHfRQ',
    appId: '1:1040158565025:android:e756cd3ca244bfd8b206e0',
    messagingSenderId: '1040158565025',
    projectId: 'clg-app-bf91b',
    storageBucket: 'clg-app-bf91b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7h23rcdGr_iqyOxNyzoNLgHPI0IY8Ww',
    appId: '1:1040158565025:ios:aa1defd82b14efbeb206e0',
    messagingSenderId: '1040158565025',
    projectId: 'clg-app-bf91b',
    storageBucket: 'clg-app-bf91b.firebasestorage.app',
    iosBundleId: 'com.example.noDoubt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA15thrGsTgKOdtMqFsUeJEuRE9Z3b6gMY',
    appId: '1:549553278454:web:c2bdcc67dc6254e334cbd7',
    messagingSenderId: '549553278454',
    projectId: 'no-doubt-f8f3e',
    authDomain: 'no-doubt-f8f3e.firebaseapp.com',
    storageBucket: 'no-doubt-f8f3e.firebasestorage.app',
  );
}
 